project:
  type: website

website:
  title: "Effect of Noisy Encoding on Big Data and Health Services Research"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/timothyhartzog
      - icon: twitter
        href: https://twitter.com/timothyhartzog
        
format:
  html:
    theme: zypher
    css: styles.css

editor: visual

